apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver-operator
  namespace: openshift-kube-apiserver-operator
spec:
  groups:
    - name: cluster-version
      rules:
        - alert: TechPreviewNoUpgrade
          annotations:
            message: Cluster has enabled tech preview features that will prevent upgrades.
          expr: |
            cluster_feature_set{name!="", namespace="openshift-kube-apiserver-operator"} == 0
          for: 10m
          labels:
            severity: warning
