apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-kube-apiserver
  namespace: openshift-kube-apiserver
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      metricRelabelings:
        - action: drop
          regex: etcd_(debugging|disk|request|server).*
          sourceLabels:
            - __name__
      port: https
      scheme: https
      tlsConfig:
        # TODO where do you mount the service-ca.crt?
        insecureSkipVerify: true
        serverName: apiserver.openshift-kube-apiserver.svc
  jobLabel: component
  namespaceSelector:
    matchNames:
      - openshift-kube-apiserver
  selector:
    matchLabels:
      app: openshift-kube-apiserver
