apiVersion: v1
kind: Service
metadata:
  namespace: openshift-kube-apiserver
  name: apiserver
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
spec:
  type: ClusterIP
  selector:
    app: openshift-kube-apiserver
  ports:
  - name: https
    port: 443
    targetPort: 6443
