apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-kubeconfig-client-ca
  namespace: openshift-config
  labels:
    "auth.openshift.io/managed-certificate-type": ca-bundle
data:
  ca-bundle.crt: |
    {{ .Assets | load "admin-kubeconfig-ca-bundle.crt" | indent 4 }}

