apiVersion: v1
kind: ConfigMap
metadata:
  name: initial-temporary-client-ca
  labels:
    "auth.openshift.io/managed-certificate-type": ca-bundle
  namespace: openshift-kube-apiserver-operator
data:
  ca-bundle.crt: |
    {{ .Assets | load "kube-apiserver-complete-client-ca-bundle.crt" | indent 4 }}

