apiVersion: v1
kind: Secret
metadata:
  name: service-network-serving-signer
  namespace: openshift-kube-apiserver-operator
  labels:
    "auth.openshift.io/managed-certificate-type": signer
  annotations:
    "auth.openshift.io/certificate-not-before": {{ .Assets | load "kube-apiserver-service-network-signer.crt" | notBefore }}
    "auth.openshift.io/certificate-not-after": {{ .Assets | load "kube-apiserver-service-network-signer.crt" | notAfter }}
    "auth.openshift.io/certificate-issuer": {{ .Assets | load "kube-apiserver-service-network-signer.crt" | issuer }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "kube-apiserver-service-network-signer.crt" | base64 }}
  tls.key: {{ .Assets | load "kube-apiserver-service-network-signer.key" | base64 }}
